const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const html = fs.readFileSync(path.join(__dirname, 'prototype.html'), 'utf8');
const registry = JSON.parse(html.match(/<script id="registry" type="application\/json">([\s\S]*?)<\/script>/)[1]);
const script = html.match(/<script>\s*([\s\S]*?)<\/script>/)[1];
new vm.Script(script);
const declaration = script.slice(script.indexOf('const model='), script.indexOf('window.prototypeModel=model;'));
const model = vm.runInNewContext(declaration + ';model');
const rules = {zoom:'always', discord:'never', unlisted:'never'};
const keys = registry.map(t=>t.id);
assert.equal(new Set(keys).size, keys.length);
assert.ok(keys.includes('zoom') && !keys.includes('google_meet_web'));
assert.ok(registry.every(t=>t.name.length>0));
assert.equal(model.bulk({zoom:'ask',discord:'ask'}), 'ask');
assert.equal(model.bulk(rules), '');
assert.equal(model.bulk({}), '');
const changed = model.patchRule(rules, 'zoom', 'ask', ['zoom','discord']);
assert.equal(changed.zoom, 'ask');
assert.equal(changed.discord, 'never');
assert.equal(rules.zoom, 'always');
const all = model.patchRule(rules, 'all', 'always', ['zoom','discord']);
assert.equal(all.unlisted, 'never');
assert.equal(all.discord, 'always');
assert.throws(()=>model.patchRule(rules,'unknown','always',['zoom']));
assert.throws(()=>model.patchRule(rules,'zoom','sometimes',['zoom']));
const prefs={reminders:true,offsetMinutes:5,showTitles:false,sound:true};
assert.equal(model.patchPreference(prefs,'sound',false).showTitles,false);
assert.equal(model.patchPreference(prefs,'reminders',false).offsetMinutes,5);
assert.equal(prefs.sound,true);
assert.throws(()=>model.patchPreference(prefs,'offsetMinutes',3));
assert.throws(()=>model.patchPreference(prefs,'sound','false'));
assert.throws(()=>model.patchPreference(prefs,'owner','someone'));
assert.ok(!/\b(fetch|XMLHttpRequest|WebSocket|localStorage)\b/.test(script));
console.log(`PASS: prototype model, validation, unchanged values, ${registry.length} named targets, no external I/O; JS parses.`);
