<Project>
  <PropertyGroup>
    <PlatformToolset Condition="'$(PlatformToolset)' == ''">v143</PlatformToolset>
    <LanguageStandard Condition="'$(LanguageStandard)' == ''">stdcpp20</LanguageStandard>
    <WindowsTargetPlatformMinVersion Condition="'$(WindowsTargetPlatformMinVersion)' == ''">10.0.19045.0</WindowsTargetPlatformMinVersion>
    <WindowsTargetPlatformVersion Condition="'$(WindowsTargetPlatformVersion)' == ''">10.0.26100.0</WindowsTargetPlatformVersion>
    <UACExecutionLevel>AsInvoker</UACExecutionLevel>
    <EnablePreviewFeatures>false</EnablePreviewFeatures>
    <OutDir>$(MSBuildThisFileDirectory)out\$(Platform)\$(Configuration)\</OutDir>
    <IntDir>$(MSBuildThisFileDirectory)out\obj\$(MSBuildProjectName)\$(Platform)\$(Configuration)\</IntDir>
    <GenerateManifest>true</GenerateManifest>
    <WarningLevel>Level4</WarningLevel>
    <TreatWarningAsError>true</TreatWarningAsError>
  </PropertyGroup>

  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalOptions>/permissive- /W4 %(AdditionalOptions)</AdditionalOptions>
      <PreprocessorDefinitions>WIN32_LEAN_AND_MEAN;NOMINMAX;_WIN32_WINNT=0x0A00;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <ConformanceMode>true</ConformanceMode>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>
