public enum AuditEventName: String, Codable, Sendable {
    case permissionChanged = "permission.changed"
    case browserTargetEvidenceRecorded = "browser_target_evidence.recorded"
    case streamHealthFailed = "stream_health.failed"
    case debugClipCleanupCompleted = "debug_clip.cleanup_completed"
    case captureStarted = "capture.started"
    case captureStopped = "capture.stopped"
    case recordingStartRequested = "recording.start_requested"
    case recordingStartBlocked = "recording.start_blocked"
    case recordingStarted = "recording.started"
    case recordingStopRequested = "recording.stop_requested"
    case recordingStopped = "recording.stopped"
    case recordingFailed = "recording.failed"
    case recordingIndicatorLost = "recording.indicator_lost"
    case recordingStorageBlocked = "recording.storage_blocked"
    case localRecordingSaved = "local_recording.saved"
    case localRecordingDegraded = "local_recording.degraded"
    case localRecordingFailed = "local_recording.failed"
    case assistedAutoStartReadinessRecorded = "assisted_auto_start.readiness_recorded"
    case localBufferEntered = "local_buffer.entered"
    case uploadQueued = "upload.queued"
    case uploadRetrying = "upload.retrying"
    case uploadUploaded = "upload.uploaded"
    case uploadBlocked = "upload.blocked"
    case uploadFailed = "upload.failed"
    case localPurgeAcknowledged = "local_purge.acknowledged"
}
