included:
  - RecApp
  - Shared

excluded:
  - .build
  - DerivedData
  - Installer

disabled_rules:
  - trailing_comma

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional

line_length:
  warning: 100
  error: 120
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 450

file_length:
  warning: 500
  error: 800

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id

reporter: "xcode"
