BLOCKED_CONFIG = "blocked_config"
BLOCKED_TEMPORAL_UNAVAILABLE = "blocked_temporal_unavailable"
BLOCKED_MEDIASCRIBE_UNAVAILABLE = "blocked_mediascribe_unavailable"
BLOCKED_MISSING_ARTIFACTS = "blocked_missing_artifacts"
BLOCKED_INVALID_MEETING_STATE = "blocked_invalid_meeting_state"
BLOCKED_UNAUTHORIZED = "blocked_unauthorized"
BLOCKED_AUDIO_TOO_LARGE = "blocked_audio_too_large"

MEDIASCRIBE_AUTH_FAILED = "mediascribe_auth_failed"
MEDIASCRIBE_VALIDATION_FAILED = "mediascribe_validation_failed"
MEDIASCRIBE_PAYLOAD_TOO_LARGE = "mediascribe_payload_too_large"
MEDIASCRIBE_RATE_LIMITED = "mediascribe_rate_limited"
MEDIASCRIBE_SERVER_ERROR = "mediascribe_server_error"
MEDIASCRIBE_TIMEOUT = "mediascribe_timeout"
MEDIASCRIBE_RESULT_NOT_READY = "mediascribe_result_not_ready"
MEDIASCRIBE_JOB_FAILED = "mediascribe_job_failed"
MEDIASCRIBE_MALFORMED_RESPONSE = "mediascribe_malformed_response"
UNKNOWN_DEPENDENCY_STATUS = "unknown_dependency_status"
RESULT_IMPORT_FAILED = "result_import_failed"

RESTART_RESUMED = "restart_resumed"
DUPLICATE_WORKFLOW_REUSED = "duplicate_workflow_reused"
